-- create dept table
create table dept(
    deptno int primary key,
    dname varchar(20),
    loc varchar(20),
    branchno int
);
-- insert data into dept table
insert into dept values(10, 'ACCOUNTING', 'NEW YORK', 1);
insert into dept values(20, 'RESEARCH', 'DALLAS', 2);
insert into dept values(30, 'SALES', 'CHICAGO', 3);
insert into dept values(40, 'OPERATIONS', 'BOSTON', 4);

SELECT * FROM dept WHERE deptno = 10;


select * from whoami;



select * from tbl_book;


create table users(
userId  NUMERIC(3) generated by default as identity primary key , 
userName varchar2(16) not null,
email   varchar2(50) not null
);


insert into users (userName,email) values('Amit','amit@example.com');
insert into users (userName,email) values('Ajit','ajit@example.com');
insert into users (userName,email) values('Ankit','ankit@example.com');

select * from users;
-- write a plsql code to get the user with id 1
DECLARE
    user_name users.userName%type;
    user_email users.email%type;
begin

    select userName,email into user_name,user_email from users;
    dbms_output.put_line('User Name : ' || user_name || ' User Email : ' || user_email);
end;
/